export const GET_ERRORS = "GET_ERRORS";

//USER
export const REGISTER = "REGISTER";
export const LOGIN_USER = "LOGIN_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const GET_ADDRESS = "GET_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";

//CATEGORY
export const GET_CATEGORY = "GET_CATEGORY";
export const SEARCH_BAR = "SEARCH_BAR";

//CATALOG
export const GET_ITEMS = "GET_ITEMS";
export const GET_ITEM_DETAIL = "GET_ITEM_DETAIL";
export const GET_CART = "GET_CART";
export const ADD_TO_CART = "ADD_TO_CART";

//cart
export const ADD_QTY = "ADD_QTY";
export const SUB_QTY = "SUB_QTY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const GET_TOTAL_PRICE = "GET_TOTAL_PRICE";
export const GET_TOTAL_ITEM = "GET_TOTAL_ITEM";
export const CHECK_OUT = "CHECK_OUT";
export const MAKE_PAYMENT = "MAKE_PAYMENT";
export const COURIER_SELECTED = "COURIER_SELECTED";
export const PROCESS_ORDER = "PLACE_ORDER";


//MERCHANT
export const GET_CURRENT_MERCHANT = "GET_CURRENT_MERCHANT";
export const GET_CURRENT_MERCHANT_ITEMS = "GET_CURRENT_MERCHANT_ITEMS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_CURRENT_PRODUCT_FOR_UPDATE = "GET_CURRENT_PRODUCT_FOR_UPDATE";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_WITH_IMAGE = "UPDATE_PRODUCT_WITH_IMAGE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_ALL_ORDERS_MERCHANT = "GET_ALL_ORDERS_MERCHANT";
export const ACC_REJ_ORDER = "ACC_REJ_ORDER";

//COURIER
export const GET_COURIERS = "GET_COURIERS";

//TESTIMONIAL
export const CREATE_RATING = "CREATE_RATING";
export const GET_RATING = "GET_RATING";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const GET_COMMENT = "GET_COMMENT";

//INVOICE
export const GET_ALL_ORDERS = "GET_ORDERS";
export const FINISH_ORDER = "FINISH_ORDER";

//VOUCHER
export const APPLY_VOUCHER = "APPLY_VOUCHER";
export const CANCEL_APPLY_VOUCHER = "CANCEL_APPLY_VOUCHER";
export const LOAD_VOUCHERS = "LOAD_VOUCHERS";
export const GET_VOUCHER_STATUS = "GET_VOUCHER_STATUS";
